#!/bin/bash
./tokenize /mnt/work/training_data/b_3_out_4.txt > /mnt/work/training_data.tok/b_3_out_4.tok.txt
./tokenize /mnt/work/training_data/b_5_out_10.txt > /mnt/work/training_data.tok/b_5_out_10.tok.txt
./tokenize /mnt/work/training_data/b_4_out_9.txt > /mnt/work/training_data.tok/b_4_out_9.tok.txt
./tokenize /mnt/work/training_data/b_1_out_16.txt > /mnt/work/training_data.tok/b_1_out_16.tok.txt
./tokenize /mnt/work/training_data/b_3_out_6.txt > /mnt/work/training_data.tok/b_3_out_6.tok.txt
./tokenize /mnt/work/training_data/news.2009.en.shuffled > /mnt/work/training_data.tok/news.2009.en.tok.shuffled
./tokenize /mnt/work/training_data/b_3_out_16.txt > /mnt/work/training_data.tok/b_3_out_16.tok.txt
./tokenize /mnt/work/training_data/b_1_out_2.txt > /mnt/work/training_data.tok/b_1_out_2.tok.txt
./tokenize /mnt/work/training_data/b_4_out_8.txt > /mnt/work/training_data.tok/b_4_out_8.tok.txt
./tokenize /mnt/work/training_data/b_1_out_3.txt > /mnt/work/training_data.tok/b_1_out_3.tok.txt
./tokenize /mnt/work/training_data/b_1_out_17.txt > /mnt/work/training_data.tok/b_1_out_17.tok.txt
./tokenize /mnt/work/training_data/b_5_out_16.txt > /mnt/work/training_data.tok/b_5_out_16.tok.txt
./tokenize /mnt/work/training_data/b_1_out_11.txt > /mnt/work/training_data.tok/b_1_out_11.tok.txt
./tokenize /mnt/work/training_data/b_2_out_15.txt > /mnt/work/training_data.tok/b_2_out_15.tok.txt
./tokenize /mnt/work/training_data/b_5_out_0.txt > /mnt/work/training_data.tok/b_5_out_0.tok.txt
./tokenize /mnt/work/training_data/b_2_out_16.txt > /mnt/work/training_data.tok/b_2_out_16.tok.txt
./tokenize /mnt/work/training_data/b_3_out_17.txt > /mnt/work/training_data.tok/b_3_out_17.tok.txt
./tokenize /mnt/work/training_data/b_2_out_6.txt > /mnt/work/training_data.tok/b_2_out_6.tok.txt
./tokenize /mnt/work/training_data/b_5_out_1.txt > /mnt/work/training_data.tok/b_5_out_1.tok.txt
./tokenize /mnt/work/training_data/b_1_out_15.txt > /mnt/work/training_data.tok/b_1_out_15.tok.txt
./tokenize /mnt/work/training_data/b_4_out_14.txt > /mnt/work/training_data.tok/b_4_out_14.tok.txt
./tokenize /mnt/work/training_data/b_4_out_3.txt > /mnt/work/training_data.tok/b_4_out_3.tok.txt
./tokenize /mnt/work/training_data/b_1_out_8.txt > /mnt/work/training_data.tok/b_1_out_8.tok.txt
./tokenize /mnt/work/training_data/b_1_out_9.txt > /mnt/work/training_data.tok/b_1_out_9.tok.txt
./tokenize /mnt/work/training_data/b_5_out_18.txt > /mnt/work/training_data.tok/b_5_out_18.tok.txt
./tokenize /mnt/work/training_data/b_4_out_1.txt > /mnt/work/training_data.tok/b_4_out_1.tok.txt
./tokenize /mnt/work/training_data/b_3_out_0.txt > /mnt/work/training_data.tok/b_3_out_0.tok.txt
./tokenize /mnt/work/training_data/b_2_out_17.txt > /mnt/work/training_data.tok/b_2_out_17.tok.txt
./tokenize /mnt/work/training_data/b_3_out_15.txt > /mnt/work/training_data.tok/b_3_out_15.tok.txt
./tokenize /mnt/work/training_data/b_4_out_12.txt > /mnt/work/training_data.tok/b_4_out_12.tok.txt
./tokenize /mnt/work/training_data/b_2_out_3.txt > /mnt/work/training_data.tok/b_2_out_3.tok.txt
./tokenize /mnt/work/training_data/b_1_out_4.txt > /mnt/work/training_data.tok/b_1_out_4.tok.txt
./tokenize /mnt/work/training_data/news.2010.en.shuffled > /mnt/work/training_data.tok/news.2010.en.tok.shuffled
./tokenize /mnt/work/training_data/b_4_out_6.txt > /mnt/work/training_data.tok/b_4_out_6.tok.txt
./tokenize /mnt/work/training_data/b_4_out_19.txt > /mnt/work/training_data.tok/b_4_out_19.tok.txt
./tokenize /mnt/work/training_data/b_1_out_6.txt > /mnt/work/training_data.tok/b_1_out_6.tok.txt
./tokenize /mnt/work/training_data/b_5_out_20.txt > /mnt/work/training_data.tok/b_5_out_20.tok.txt
./tokenize /mnt/work/training_data/b_4_out_10.txt > /mnt/work/training_data.tok/b_4_out_10.tok.txt
./tokenize /mnt/work/training_data/news.2011.en.shuffled > /mnt/work/training_data.tok/news.2011.en.tok.shuffled
./tokenize /mnt/work/training_data/b_4_out_4.txt > /mnt/work/training_data.tok/b_4_out_4.tok.txt
./tokenize /mnt/work/training_data/b_4_out_11.txt > /mnt/work/training_data.tok/b_4_out_11.tok.txt
./tokenize /mnt/work/training_data/b_4_out_16.txt > /mnt/work/training_data.tok/b_4_out_16.tok.txt
./tokenize /mnt/work/training_data/b_3_out_5.txt > /mnt/work/training_data.tok/b_3_out_5.tok.txt
./tokenize /mnt/work/training_data/b_1_out_7.txt > /mnt/work/training_data.tok/b_1_out_7.tok.txt
./tokenize /mnt/work/training_data/b_1_out_19.txt > /mnt/work/training_data.tok/b_1_out_19.tok.txt
./tokenize /mnt/work/training_data/b_5_out_4.txt > /mnt/work/training_data.tok/b_5_out_4.tok.txt
./tokenize /mnt/work/training_data/b_3_out_2.txt > /mnt/work/training_data.tok/b_3_out_2.tok.txt
./tokenize /mnt/work/training_data/b_1_out_13.txt > /mnt/work/training_data.tok/b_1_out_13.tok.txt
./tokenize /mnt/work/training_data/b_5_out_15.txt > /mnt/work/training_data.tok/b_5_out_15.tok.txt
./tokenize /mnt/work/training_data/b_3_out_7.txt > /mnt/work/training_data.tok/b_3_out_7.tok.txt
./tokenize /mnt/work/training_data/b_5_out_2.txt > /mnt/work/training_data.tok/b_5_out_2.tok.txt
./tokenize /mnt/work/training_data/b_1_out_5.txt > /mnt/work/training_data.tok/b_1_out_5.tok.txt
./tokenize /mnt/work/training_data/b_4_out_2.txt > /mnt/work/training_data.tok/b_4_out_2.tok.txt
./tokenize /mnt/work/training_data/b_1_out_10.txt > /mnt/work/training_data.tok/b_1_out_10.tok.txt
./tokenize /mnt/work/training_data/b_2_out_12.txt > /mnt/work/training_data.tok/b_2_out_12.tok.txt
./tokenize /mnt/work/training_data/b_2_out_9.txt > /mnt/work/training_data.tok/b_2_out_9.tok.txt
./tokenize /mnt/work/training_data/b_2_out_13.txt > /mnt/work/training_data.tok/b_2_out_13.tok.txt
./tokenize /mnt/work/training_data/b_3_out_3.txt > /mnt/work/training_data.tok/b_3_out_3.tok.txt
./tokenize /mnt/work/training_data/b_4_out_20.txt > /mnt/work/training_data.tok/b_4_out_20.tok.txt
./tokenize /mnt/work/training_data/b_2_out_11.txt > /mnt/work/training_data.tok/b_2_out_11.tok.txt
./tokenize /mnt/work/training_data/b_5_out_21.txt > /mnt/work/training_data.tok/b_5_out_21.tok.txt
./tokenize /mnt/work/training_data/b_3_out_9.txt > /mnt/work/training_data.tok/b_3_out_9.tok.txt
./tokenize /mnt/work/training_data/b_4_out_18.txt > /mnt/work/training_data.tok/b_4_out_18.tok.txt
./tokenize /mnt/work/training_data/b_5_out_7.txt > /mnt/work/training_data.tok/b_5_out_7.tok.txt
./tokenize /mnt/work/training_data/b_2_out_10.txt > /mnt/work/training_data.tok/b_2_out_10.tok.txt
./tokenize /mnt/work/training_data/b_3_out_14.txt > /mnt/work/training_data.tok/b_3_out_14.tok.txt
./tokenize /mnt/work/training_data/b_3_out_12.txt > /mnt/work/training_data.tok/b_3_out_12.tok.txt
./tokenize /mnt/work/training_data/b_3_out_11.txt > /mnt/work/training_data.tok/b_3_out_11.tok.txt
./tokenize /mnt/work/training_data/b_5_out_6.txt > /mnt/work/training_data.tok/b_5_out_6.tok.txt
./tokenize /mnt/work/training_data/b_2_out_2.txt > /mnt/work/training_data.tok/b_2_out_2.tok.txt
./tokenize /mnt/work/training_data/b_5_out_9.txt > /mnt/work/training_data.tok/b_5_out_9.tok.txt
./tokenize /mnt/work/training_data/b_5_out_5.txt > /mnt/work/training_data.tok/b_5_out_5.tok.txt
./tokenize /mnt/work/training_data/b_1_out_1.txt > /mnt/work/training_data.tok/b_1_out_1.tok.txt
./tokenize /mnt/work/training_data/b_2_out_18.txt > /mnt/work/training_data.tok/b_2_out_18.tok.txt
./tokenize /mnt/work/training_data/b_1_out_14.txt > /mnt/work/training_data.tok/b_1_out_14.tok.txt
./tokenize /mnt/work/training_data/b_3_out_10.txt > /mnt/work/training_data.tok/b_3_out_10.tok.txt
./tokenize /mnt/work/training_data/b_2_out_5.txt > /mnt/work/training_data.tok/b_2_out_5.tok.txt
./tokenize /mnt/work/training_data/b_1_out_0.txt > /mnt/work/training_data.tok/b_1_out_0.tok.txt
./tokenize /mnt/work/training_data/b_3_out_18.txt > /mnt/work/training_data.tok/b_3_out_18.tok.txt
./tokenize /mnt/work/training_data/b_4_out_15.txt > /mnt/work/training_data.tok/b_4_out_15.tok.txt
./tokenize /mnt/work/training_data/b_3_out_13.txt > /mnt/work/training_data.tok/b_3_out_13.tok.txt
./tokenize /mnt/work/training_data/b_5_out_19.txt > /mnt/work/training_data.tok/b_5_out_19.tok.txt
./tokenize /mnt/work/training_data/b_1_out_18.txt > /mnt/work/training_data.tok/b_1_out_18.tok.txt
./tokenize /mnt/work/training_data/b_4_out_5.txt > /mnt/work/training_data.tok/b_4_out_5.tok.txt
./tokenize /mnt/work/training_data/b_2_out_1.txt > /mnt/work/training_data.tok/b_2_out_1.tok.txt
./tokenize /mnt/work/training_data/b_5_out_11.txt > /mnt/work/training_data.tok/b_5_out_11.tok.txt
./tokenize /mnt/work/training_data/b_2_out_7.txt > /mnt/work/training_data.tok/b_2_out_7.tok.txt
./tokenize /mnt/work/training_data/b_3_out_1.txt > /mnt/work/training_data.tok/b_3_out_1.tok.txt
./tokenize /mnt/work/training_data/b_4_out_17.txt > /mnt/work/training_data.tok/b_4_out_17.tok.txt
./tokenize /mnt/work/training_data/b_3_out_8.txt > /mnt/work/training_data.tok/b_3_out_8.tok.txt
./tokenize /mnt/work/training_data/b_4_out_7.txt > /mnt/work/training_data.tok/b_4_out_7.tok.txt
./tokenize /mnt/work/training_data/b_2_out_0.txt > /mnt/work/training_data.tok/b_2_out_0.tok.txt
./tokenize /mnt/work/training_data/b_2_out_14.txt > /mnt/work/training_data.tok/b_2_out_14.tok.txt
./tokenize /mnt/work/training_data/b_1_out_20.txt > /mnt/work/training_data.tok/b_1_out_20.tok.txt
./tokenize /mnt/work/training_data/b_4_out_0.txt > /mnt/work/training_data.tok/b_4_out_0.tok.txt
./tokenize /mnt/work/training_data/b_5_out_3.txt > /mnt/work/training_data.tok/b_5_out_3.tok.txt
./tokenize /mnt/work/training_data/news.2008.en.shuffled > /mnt/work/training_data.tok/news.2008.en.tok.shuffled
./tokenize /mnt/work/training_data/news.2007.en.shuffled > /mnt/work/training_data.tok/news.2007.en.tok.shuffled
./tokenize /mnt/work/training_data/b_5_out_12.txt > /mnt/work/training_data.tok/b_5_out_12.tok.txt
./tokenize /mnt/work/training_data/b_5_out_14.txt > /mnt/work/training_data.tok/b_5_out_14.tok.txt
./tokenize /mnt/work/training_data/b_1_out_12.txt > /mnt/work/training_data.tok/b_1_out_12.tok.txt
./tokenize /mnt/work/training_data/b_4_out_13.txt > /mnt/work/training_data.tok/b_4_out_13.tok.txt
./tokenize /mnt/work/training_data/b_5_out_13.txt > /mnt/work/training_data.tok/b_5_out_13.tok.txt
./tokenize /mnt/work/training_data/b_5_out_17.txt > /mnt/work/training_data.tok/b_5_out_17.tok.txt
./tokenize /mnt/work/training_data/b_2_out_8.txt > /mnt/work/training_data.tok/b_2_out_8.tok.txt
./tokenize /mnt/work/training_data/b_5_out_8.txt > /mnt/work/training_data.tok/b_5_out_8.tok.txt
./tokenize /mnt/work/training_data/b_2_out_4.txt > /mnt/work/training_data.tok/b_2_out_4.tok.txt
