import os
import copy

model_name = 'wrmV14'
params = { 'model_name': model_name,
					 'output_location': './output/%s/'%model_name,
					 'null_sample_factor': 0,  # <0= equal null as non null per sentence, 0 = don't do anything, >0 = factor
					 'num_words_before': 10,
					 'num_words_after': 10,
					 'embedding_size': 200,
					 'conv_num_features': [[200, 200, 200]],
					 'conv_widths': [[2,2,2]],
					 'conv_keep_probs': None,
					 'all_lowercase': True,
					 'use_no_conv_path': True,                       # enable embedding pass through to second stage
					 'mlp_config': [256],
					 'bipass_conv': False,
					 'mlp_activations': 'sigmoid',
					 'mlp_keep_probs': 0.9,
					 'embedding_keep_prob': 0.8,
					 'embedding_device': '/cpu:0',
					 'batch_size': 8192,
					 'learning_rate': 0.0005,
					 'start_token': '<S>',
					 'unk_token': 'unk',
#					 'max_vocab_size': 50000,
					 'keywords': {},
					 'keyword_buckets': [
						 [('who', "'s"), 'whose'],
						 ['than','then'],
						 ['their','there',('they',"'re")],
						 ['accept','except'],
						 ['accepted','excepted'],
						 ['advice', 'advise'],
						 ['affect','effect'],
						 ['among', 'between'],
						 ['assure','ensure','insure'],
						 ['breath', 'breathe'],
						 ['disinterested', 'uninterested'],
							['emigrate','immigrate'],
						 ['i.e.','e.g.'],
						 ['empathy','sympathy'],
						 ['farther','further'],
						 ['flaunt','flout'],
						 ['historic','historical'],
						 ['imply','infer'],
						 [('it',"'s"),'its','it'],
						 ['lay','lie', 'lei', 'lye'],
						 ['loose', 'lose'],
						 ['principal','principle'],
						 ['inquiry','enquiry'],
						 ['elicit', 'illicit'],
						 ['too','to','two'],
						 ['pear','pair', 'pare'],
						 ['pears','pairs'],
						 ['male','mail'],
						 ['males','mails'],
						 ['holy', 'wholly', 'holey', 'holly'],
						 ['half', 'have'],
						 ['ad','add', 'ads', 'adds'],
						 ['hall', 'haul'],
						 ['steal','steel'],
						 ['lets', ('let',"'s")],
						 ['bear','bare'],
						 ['plain','plane'],
						 ['for','four','fore','forth','fourth'],
#						 ['may'], ['march'],
#						 ['a','an','the'],
						 ['quiet','quite'],
						 ['sole','soul'],
						 ['soles','souls'],
						 ['your',('you',"'re")],
						 [('all','right'),'alright'],
						 [('some','time'),'sometime','sometimes'],
						 ['everyday',('every','day')],
#						 ['i'],
						 ['besides','beside'],
						 ['around','about'],
##						 ['aerie', 'airy'],
##						 ['ail', 'ale'],
##						 ['all', 'awl'],
						 ['allowed', 'aloud'],
						 ['altar', 'alter'],
						 ['arc', 'ark'],
						 ['ascent', 'assent'],
						 ['attendance', 'attendants'],
						 ['axes', 'axis'],
						 ['aye', 'eye'],
						 ['bail', 'bale'],
						 ['baited', 'bated'],
##						 ['bald', 'bawled'],
##						 ['ball', 'bawl'],
						 ['band', 'banned'],
						 ['bard', 'barred'],
						 ['baron', 'barren'],
						 ['base', 'bass'],
#						 ['based', 'baste'],
						 ['be', 'bee'],
						 ['beach', 'beech'],
						 ['beat', 'beet'],
						 ['beau', 'bow', 'bough'],
						 ['beer', 'bier'],
						 ['bell', 'belle'],
						 ['berry', 'bury'],
						 ['berth', 'birth'],
						 ['billed', 'build'],
						 ['blew', 'blue'],
						 ['bloc', 'block'],
						 ['boar', 'bore'],
						 ['board', 'bored'],
						 ['boarder', 'border'],
						 ['bold', 'bowled'],
						 ['bolder', 'boulder'],
##						 ['bootie', 'booty'],
						 ['born', 'borne'],
						 ['burro', 'burrow'],
##						 ['braid', 'brayed'],
						 ['brake', 'break'],
						 ['bread', 'bred'],
						 ['brewed', 'brood'],
						 ['brews', 'bruise'],
						 ['bridal', 'bridle'],
						 ['broach', 'brooch'],
						 ['brows', 'browse'],
						 ['but', 'butt'],
						 ['buy', 'bye'],
						 ['caddie', 'caddy'],
##						 ['callous', 'callus'],
						 ['canon', 'cannon'],
						 ['canter', 'cantor'],
						 ['canvas', 'canvass'],
						 ['capital', 'capitol'],
						 ['carat', 'carrot'],
##						 ['carol', 'carrel'],
						 ['cast', 'caste'],
						 ['censor', 'sensor'],
						 ['cereal', 'serial'],
						 ['chance', 'chants'],
						 ['chased', 'chaste'],
##						 ['cheap', 'cheep'],
						 ['chews', 'choose'],
						 ['chilli', 'chilly'],
##						 ['choir', 'quire'],
						 ['choral', 'coral'],
##						 ['chord', 'cored'],
						 ['chute', 'shoot'],
						 ['cite', 'sight'],
						 ['clause', 'claws'],
						 ['close', 'clothes'],
						 ['coarse', 'course'],
						 ['complement', 'compliment'],
						 ['council', 'counsel'],
						 ['coward', 'cowered'],
						 ['creak', 'creek'],
#						 ['crewel', 'cruel'],			# not in our dataset at all!
						 ['crews', 'cruise'],
						 ['cue', 'queue'],
##						 ['currant', 'current'],
						 ['cygnet', 'signet'],
						 ['cymbal', 'symbol'],
						 ['dam', 'damn'],
						 ['days', 'daze'],
						 ['dear', 'deer'],
						 ['dense', 'dents'],
						 ['desert', 'dessert'],
						 ['dew', 'due'],
						 ['die', 'dye'],
						 ['disburse', 'disperse'],
						 ['discreet', 'discrete'],
						 ['doe', 'dough'],
						 ['does', 'doze'],
						 ['done', 'dun'],
						 ['dual', 'duel'],
						 ['dyeing', 'dying'],
						 ['earn', 'urn'],
##						 ['eave', 'eve'],
						 ['eek', 'eke'],
						 ['eight', 'ate'],
						 ['ewe', 'you'],
						 ['ewes', 'yews', 'use'],
						 ['faint', 'feint'],
						 ['fair', 'fare'],
						 ['faun', 'fawn'],
						 ['feat', 'feet'],
						 ['fined', 'find'],
						 ['fir', 'fur'],
						 ['fisher', 'fissure'],
						 ['flair', 'flare'],
						 ['flea', 'flee'],
						 ['flew', 'flue'],
						 ['floe', 'flow'],
						 ['flour', 'flower'],
##						 ['foaled', 'fold'],
						 ['foreword', 'forward'],
						 ['foul', 'fowl'],
##						 ['fouls', 'fowls'],
						 ['franc', 'frank'],
						 ['freeze', 'frieze'],
						 ['friar', 'fryer'],
						 ['gaff', 'gaffe'],
						 ['gait', 'gate'],
##						 ['gamble', 'gambol'],
						 ['genes', 'jeans'],
						 ['gibe', 'jibe'],
						 ['gild', 'guild'],
						 ['gilt', 'guilt'],
						 ['knew', 'new', 'gnu'],
##						 ['gofer', 'gopher'],
						 ['gorilla', 'guerrilla'],
						 ['gourd', 'gored'],
						 ['grate', 'great'],
						 ['grill', 'grille'],
						 ['grisly', 'grizzly'],
						 ['groan', 'grown'],
						 ['guessed', 'guest'],
						 ['guise', 'guys'],
						 ['hail', 'hale'],
						 ['hair', 'hare'],
						 ['hangar', 'hanger'],
						 ['hart', 'heart'],
						 ['hay', 'hey'],
						 ['heal', 'heel'],
						 ['hear', 'here'],
						 ['heard', 'herd'],
						 ['heir', 'air'],
						 ['heroin', 'heroine'],
						 ['hew', 'hue'],
						 ['hi', 'high'],
						 ['him', 'hymn'],
						 ['ho', 'hoe'],
						 ['hoard', 'horde'],#, 'whored'],
						 ['hoarse', 'horse'],
						 ['hoes', 'hose'],
						 ['hole', 'whole'],
						 ['hostel', 'hostile'],
						 ['idle', 'idol'],
						 ['in', 'inn'],
						 ['incidence', 'incidents'],
						 ['intense', 'intents'],
						 ['isle', 'aisle'],
						 ['islet', 'eyelet'],
##						 ['jam', 'jamb'],
						 ['kernel', 'colonel'],
						 ['knead', 'need'],
						 ['knight', 'night'],
						 ['knit', 'nit'],
						 ['know', 'no'],
						 ['knows', 'nose'],
						 ['lacks', 'lax'],
						 ['lain', 'lane'],
						 ['lama', 'llama'],
						 ['laps', 'lapse'],
						 ['leach', 'leech'],
						 ['lead', 'led'],
						 ['leak', 'leek'],
						 ['lean', 'lien'],
						 ['leased', 'least'],
						 ['lessen', 'lesson'],
						 ['levee', 'levy'],
						 ['links', 'lynx'],
						 ['lo', 'low'],
						 ['load', 'lode'],
						 ['loan', 'lone'],
						 ['locks', 'lox'],
						 ['loot', 'lute'],
						 ['made', 'maid'],
						 ['main', 'mane'],
						 ['maize', 'maze'],
						 ['mall', 'maul'],
						 ['manner', 'manor'],
##						 ['manners', 'manors'],
						 ['mantel', 'mantle'],
						 ['marshal', 'martial'],
						 ['mask', 'masque'],
						 ['massed', 'mast'],
						 ['meat', 'meet'],
						 ['medal', 'meddle'],
						 ['metal', 'mettle'],
##						 ['mewl', 'mule'],
						 ['mews', 'muse'],
						 ['might', 'mite'],
						 ['mince', 'mints'],
						 ['mind', 'mined'],
						 ['miner', 'minor'],
						 ['miners', 'minors'],
						 ['missal', 'missile'],
						 ['missed', 'mist'],
						 ['moan', 'mown'],
						 ['moose', 'mousse'],
						 ['morning', 'mourning'],
						 ['muscle', 'mussel'],
						 ['mustard', 'mustered'],
						 ['naval', 'navel'],
##						 ['nave', 'knave'],
	##					 ['nay', 'neigh'],
						 ['nicks', 'nix'],
						 ['none', 'nun'],
						 ['not', 'knot'],
						 ['oar', 'ore'],
						 ['ode', 'owed'],
						 ['oh', 'owe'],
						 ['one', 'won'],
						 ['oral', 'aural'],
						 ['our', 'hour'],
						 ['paced', 'paste'],
						 ['packed', 'pact'],
						 ['pail', 'pale'],
						 ['pain', 'pane'],
						 ['palette', 'pallet'],
						 ['passed', 'past'],
						 ['patience', 'patients'],
						 ['pause', 'paws'],
						 ['peace', 'piece'],
						 ['peak', 'peek'],
						 ['peal', 'peel'],
##						 ['pearl', 'purl'],
						 ['pedal', 'peddle'],
						 ['peer', 'pier'],
						 ['phase', 'faze'],
##						 ['phrase', 'frays'],
						 ['plait', 'plate'],
						 ['pleas', 'please'],
						 ['plum', 'plumb'],
						 ['pole', 'poll'],
						 ['pore', 'pour'],
						 ['praise', 'prays'],
						 ['presence', 'presents'],
						 ['pride', 'pried'],
##						 ['pries', 'prize'],
##						 ['primer', 'primmer'],
						 ['prince', 'prints'],
						 ['profit', 'prophet'],
						 ['quarts', 'quartz'],
#						 ['rabbet', 'rabbit'],
						 ['rain', 'reign'],
						 ['raise', 'rays'],
						 ['rapt', 'wrapped', 'rapped'],
						 ['real', 'reel'],
						 ['red', 'read', 'reed'],
						 ['reek', 'wreak'],
						 ['residence', 'residents'],
##						 ['retch', 'wretch'],
						 ['review', 'revue'],
						 ['ring', 'wring'],
						 ['road', 'rowed'],
						 ['roe', 'row'],
						 ['role', 'roll'],
##						 ['roomer', 'rumour'],
						 ['root', 'route'],
						 ['rose', 'rows', 'rouse'],
						 ['rote', 'wrote'],
						 ['rude', 'rued'],
						 ['rung', 'wrung'],
						 ['sac', 'sack'],
						 ['sail', 'sale'],
						 ['sane', 'seine'],
						 ['saver', 'savour'],
						 ['scene', 'seen'],
						 ['scent', 'sent'],
						 ['scull', 'skull'],
						 ['sea', 'see'],
						 ['sealing', 'ceiling'],
						 ['seam', 'seem'],
						 ['seas', 'seize'],
						 ['seed', 'cede'],
						 ['sell', 'cell'],
						 ['seller', 'cellar'],
						 ['serf', 'surf'],
						 ['serge', 'surge'],
##						 ['session', 'cession'],
						 ['sew', 'sow'],
##						 ['shearn', 'sheer'],
						 ['sheik', 'chic'],
						 ['shoe', 'shoo'],
						 ['shone', 'shown'],
						 ['sic', 'sick'],
						 ['side', 'sighed'],
						 ['sighs', 'size'],
						 ['slay', 'sleigh'],
						 ['sleight', 'slight'],
						 ['soar', 'sore'],
						 ['soared', 'sword'],
##						 ['soled', 'sold'],
						 ['some', 'sum'],
						 ['son', 'sun'],
						 ['staid', 'stayed'],
						 ['stairs', 'stares'],
						 ['stake', 'steak'],
						 ['stationary', 'stationery'],
						 ['step', 'steppe'],
						 ['stile', 'style'],
						 ['straight', 'strait'],
						 ['succour', 'sucker'],
						 ['suite', 'sweet'],
						 ['tacked', 'tact'],
						 ['tacks', 'tax'],
						 ['tail', 'tale'],
##						 ['taper', 'tapir'],
						 ['taught', 'taut'],
						 ['tea', 'tee'],
						 ['team', 'teem'],
						 ['tear', 'tier'],
						 ['teas', 'tease'],
						 ['tense', 'tents'],
						 ['tern', 'turn'],
						 ['threw', 'through'],
						 ['throes', 'throws'],
						 ['throne', 'thrown'],
						 ['thyme', 'time'],
						 ['tic', 'tick'],
						 ['tide', 'tied'],
						 ['toad', 'towed'],
						 ['toe', 'tow'],
						 ['told', 'tolled'],
						 ['tracked', 'tract'],
						 ['troop', 'troupe'],
						 ['trussed', 'trust'],
						 ['undo', 'undue'],
						 ['vain', 'vein'],
						 ['vale', 'veil'],
						 ['vice', 'vise'],
						 ['wade', 'weighed', 'wait', 'weight'],
						 ['waist', 'waste'],
						 ['waive', 'wave'],
						 ['waived', 'waved'],
						 ['wares', 'wears'],
						 ['warn', 'worn'],
						 ['way', 'weigh'],
						 ['we', 'wee'],
						 ['weak', 'week'],
						 ['wood', 'would'],
						 ['wrap', 'rap'],
						 ['wrest', 'rest'],
						 ['write', 'right'],
						 ['wry', 'rye'],
						 ['yoke', 'yolk']
					 ],
					 'mini_batches_between_checkpoint': 100,
					 'embedding_wd': 0.0001,                           # L2 WD regularization constant
					 'enable_regularization': True,
					 'monolingual_dir': '/mnt/work/1-billion-word-language-modeling-benchmark',
					 'vocab_file': '/mnt/work/1-billion-word-language-modeling-benchmark/lc_vocab.txt'
					 }

def gen_keywords(params):
	buckets = params['keyword_buckets']
	keywords = params['keywords']
	all_lowercase = params['all_lowercase']
	idx = 0
	repeat_count = 0
	id_to_keyword = []
	for bucket in buckets:
		words_to_add = []
		if not all_lowercase:
			for keyword in bucket:
				if type(keyword) is tuple:
					words_to_add.append(tuple(' '.join(list(keyword)).capitalize().split()))
				else:
					words_to_add.append(keyword.capitalize())
			print("GENERATED UPPER CASE VERSION")
		bucket += words_to_add
		for keyword in bucket:
			if keyword not in keywords:
				keywords[keyword] = [idx]+copy.deepcopy(bucket)
				keywords[keyword].remove(keyword)
				id_to_keyword.append(keyword)
				idx += 1
			else:
				print("REPEATED %s" % keyword)
				repeat_count += 1
				cur_idx = keywords[keyword][0]
				newlist = set()
				newlist = newlist.union(keywords[keyword][1:])
				newlist = newlist.union(bucket)
				keywords[keyword] = [cur_idx] + list(newlist)
				keywords[keyword].remove(keyword)
	params['id_to_keyword'] = id_to_keyword
	if repeat_count > 0:
		exit(0)
	print(id_to_keyword)
	return params

gen_keywords(params)
